language: android
jdk: oraclejdk8

# Choosing faster environment since it's a full VM.
# https://docs.travis-ci.com/user/reference/overview/
sudo: required
dist: trusty

env:
  global:
    # Notice global environment variables are available during the install phase for android >
    # components. These are the only variables that can be used in that section
    - SDK_API=26
    - BUILD_TOOLS_VERSION=26.0.0
  matrix:
    # Notice matrix environment variables are not available during the install phase for android >
    # components.
    # These CANNOT BE USED in the android > components section, only in before_script and script.
    - TEST_TYPE=unit
    - TEST_TYPE=instrumentation EMULATOR_TAG=android EMULATOR_API=16 ABI=armeabi-v7a
    - TEST_TYPE=instrumentation EMULATOR_TAG=android EMULATOR_API=19 ABI=armeabi-v7a
    - TEST_TYPE=instrumentation EMULATOR_TAG=android EMULATOR_API=21 ABI=armeabi-v7a

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools #latest
    - tools # to install Android SDK tools 25+, latest, cannot get more granular control than this
    # See https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943 for more
    # details.
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$SDK_API

  licenses:
    - 'android-sdk-license-.+'

before_script:
  - ./travis_before_script.sh

script:
  - ./gradlew assemble -PdisablePreDex;
  - ./travis_run_unit_tests.sh
  - travis_wait ./travis_set_up_emulator.sh
  - travis_wait ./travis_run_instrumentation_tests.sh
