sudo: required
language: generic

jdk: openjdk8

env:
  global:
  - ABI="google_apis;armeabi-v7a"
  - BUILD_TOOLS_VERSION=28.0.3
  - ADB_INSTALL_TIMEOUT=25
  - QEMU_AUDIO_DRV=none
  matrix:
    - EMULATOR_API=16
    - EMULATOR_API=19
    - EMULATOR_API=21
    - EMULATOR_API=24

before_install:
  - echo $JAVA_HOME

install:
  - echo $JAVA_HOME
  - export ANDROID_HOME=~/android-sdk-linux
  - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" -O android-sdk-tools.zip
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - echo $JAVA_HOME
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
  - ./gradlew dependencies || true
  - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
  - sdkmanager --list | head -20
  - sdkmanager "build-tools;$BUILD_TOOLS_VERSION" "platforms;android-$28" > /dev/null
  - sdkmanager "system-images;android-$EMULATOR_API;$ABI" > /dev/null
  - sdkmanager --list | head -15
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
  - echo $JAVA_HOME
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$EMULATOR_API;$ABI"
  - ./gradlew assembleDebugAndroidTest -PdisablePreDex --continue --stacktrace
  - $ANDROID_HOME/emulator/emulator -avd test -no-window &
  - bash android-wait-for-emulator
  - adb shell input keyevent 82

script:
  - echo $JAVA_HOME
  - ./gradlew test -PdisablePreDex --stacktrace
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace
